### ISSUE TITLE
After update on 11-stable to libressl, many packages are not working

### ISSUE THREAD

**Issue by StewGoin** [HardenedBSD/hardenedbsd-ports#100]
I have libressl-devel installed from the most recent update/upgrade, but openssl version reports:
LibreSSL 2.5.5

And many commands / packages are broken:
`root@filer:~ # curl
/usr/local/lib/libcurl.so.4: Undefined symbol "SSL_CTX_set_srp_password"`

**Comment by lattera** [comment]
@Sp1l, this issue is critical. It appears every package in the 11-STABLE repo that requires libcrypto or libssl might be broken.

**Comment by lattera** [comment]
This might be a red herring. @StewGoin, can you confirm that `pkg-static upgrade -f` fixed the problem (or `pkg upgrade -f`)?

**Comment by StewGoin** [comment]
Yeah, it seems to be resolved after I did a 
`secadm flush && pkg clean -y && pkg upgrade -f`

then a reboot.

The original `pkg upgrade` did not update nearly as many packages.

Everything seems to be working now though!

**Comment by lattera** [comment]
Closing this ticket as the user has reported success.
