### ISSUE TITLE
py3-pip - error: invalid command 'build_sphinx'

### ISSUE THREAD

**Issue by bryn1u** [HardenedBSD/hardenedbsd-ports#102]
Hello,
There is a problem with compile py3-pip. Log below. It doesn't matter if it's compiled with pie, relro, safestack. Even without any features problem shows the same. Python36 has compiled great with all security features. For example py2-pip has compiled without any problem with pie, relro and safestack features, python27 the same, has compiled great.

> root@proton:/usr/ports/devel/py3-pip # make install clean
> ===>  Building for py36-pip-9.0.1
> usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>    or: setup.py --help [cmd1 cmd2 ...]
>    or: setup.py --help-commands
>    or: setup.py cmd --help
> 
> error: invalid command 'build_sphinx'
> *** Error code 1
> 
> Stop.
> make: stopped in /usr/ports/devel/py3-pip
> root@proton:/usr/ports/devel/py3-pip # make clean
> ===>  Cleaning for py36-pip-9.0.1
> root@proton:/usr/ports/devel/py3-pip # make install clean
> ===>  License MIT accepted by the user
> ===>   py36-pip-9.0.1 depends on file: /usr/local/sbin/pkg - found
> ===> Fetching all distfiles required by py36-pip-9.0.1 for building
> ===>  Extracting for py36-pip-9.0.1
> => SHA256 Checksum OK for pypa-pip-9.0.1_GH0.tar.gz.
> ===>  Patching for py36-pip-9.0.1
> ===>  Applying FreeBSD patches for py36-pip-9.0.1
> ===>   py36-pip-9.0.1 depends on executable: sphinx-build - found
> ===>   py36-pip-9.0.1 depends on package: py36-setuptools>0 - found
> ===>   py36-pip-9.0.1 depends on file: /usr/local/bin/python3.6 - found
> ===>  Configuring for py36-pip-9.0.1
> running config
> ===>  Building for py36-pip-9.0.1
> usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>    or: setup.py --help [cmd1 cmd2 ...]
>    or: setup.py --help-commands
>    or: setup.py cmd --help
> 
> error: invalid command 'build_sphinx'
> *** Error code 1
> 
> Stop.
> make: stopped in /usr/ports/devel/py3-pip
> root@proton:/usr/ports/devel/py3-pip #

**Comment by lattera** [comment]
devel/py3-pip built fine in HardenedBSD's package build.

**Comment by fichtner** [comment]
Same as #104
