### ISSUE TITLE
`__safestack_unsafe_stack_ptr' follow - nginx

### ISSUE THREAD

**Issue by bryn1u** [HardenedBSD/hardenedbsd-ports#103]
objs/src/core/nginx.o: In function `main':
src/core/nginx.c:(.text+0x19): undefined reference to `__safestack_unsafe_stack_ptr'
src/core/nginx.c:(.text+0x3dc): undefined reference to `__safestack_unsafe_stack_ptr'
src/core/nginx.c:(.text+0x47d): undefined reference to `__safestack_unsafe_stack_ptr'
src/core/nginx.c:(.text+0x54d): undefined reference to `__safestack_unsafe_stack_ptr'
src/core/nginx.c:(.text+0x842): undefined reference to `__safestack_unsafe_stack_ptr'
objs/src/core/nginx.o:src/core/nginx.c:(.text+0x9f1): more undefined references to `__safestack_unsafe_stack_ptr' follow
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
make[2]: stopped in /usr/ports/www/nginx/work/nginx-1.12.1
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/www/nginx/work/nginx-1.12.1
*** Error code 1

Stop.
make: stopped in /usr/ports/www/nginx
root@proton:/usr/ports/www/nginx #

**Comment by lattera** [comment]
www/nginx builds fine in HardenedBSD's package builds.

**Comment by noptrix** [comment]
@bryn1u can you show me your config for www/nginx?

**Comment by bryn1u** [comment]
Hello, 

Config is deafult + SafeStack.

**Comment by noptrix** [comment]
@bryn1u Same here. Use without safestack please as it seems to be not supported for nginx atm.
