### ISSUE TITLE
py27-pip - error: invalid command 'build_sphinx'with - clear config

### ISSUE THREAD

**Issue by bryn1u** [HardenedBSD/hardenedbsd-ports#104]
Im getting error with clear config.

> Nope. I can't build with clear config. Im getting still the same error:
> root@proton:/usr/ports/devel/py-pip # 
> root@proton:/usr/ports/devel/py-pip # make reinstall clean
> ===>  License MIT accepted by the user
> ===>   py27-pip-9.0.1 depends on file: /usr/local/sbin/pkg - found
> ===> Fetching all distfiles required by py27-pip-9.0.1 for building
> ===>  Extracting for py27-pip-9.0.1
> => SHA256 Checksum OK for pypa-pip-9.0.1_GH0.tar.gz.
> ===>  Patching for py27-pip-9.0.1
> ===>  Applying FreeBSD patches for py27-pip-9.0.1
> ===>   py27-pip-9.0.1 depends on executable: sphinx-build - found
> ===>   py27-pip-9.0.1 depends on package: py27-setuptools>0 - found
> ===>   py27-pip-9.0.1 depends on file: /usr/local/bin/python2.7 - found
> ===>  Configuring for py27-pip-9.0.1
> running config
> ===>  Building for py27-pip-9.0.1
> usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>    or: setup.py --help [cmd1 cmd2 ...]
>    or: setup.py --help-commands
>    or: setup.py cmd --help
> 
> error: invalid command 'build_sphinx'
> *** Error code 1
> 
> Stop.
> make[1]: stopped in /usr/ports/devel/py-pip
> *** Error code 1
> 
> Stop.
> make: stopped in /usr/ports/devel/py-pip
> root@proton:/usr/ports/devel/py-pip #

**Comment by lattera** [comment]
devel/py-pip built fine in HardenedBSD's package build.

**Comment by bryn1u** [comment]
So how is even possible ? Always this message shows up: error: invalid command 'build_sphinx'
Could someone explain me what does mean ?

**Comment by lattera** [comment]
My guess is that with your mucking around with SafeStack, you've broken something. Please leave setting SafeStack to those who know the care that must be taken to do so. Chances are you enabled SafeStack on something that the py*-pip ports depend on, and that's causing breakages. Thus, the problem is with things you've done and not HardenedBSD.

**Comment by bryn1u** [comment]
Okey. Thank you for you advice. I will do it what you has written. It can be closed.
