### ISSUE TITLE
[LibreSSL] devel/apr1 build failure

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedbsd-ports#109]
Looks like it's failing to apply the LibreSSL patch. Log attached.

[apr-1.6.3.1.6.1.log.txt](https://github.com/HardenedBSD/hardenedbsd-ports/files/1463897/apr-1.6.3.1.6.1.log.txt)

**Comment by Sp1l** [comment]
Fixed with aad0824010a9
