### ISSUE TITLE
py-libzfs and therefore py-iocage broken

### ISSUE THREAD

**Issue by utrenkner** [HardenedBSD/hardenedbsd-ports#113]
Trying to build iocage from source failed. A build via Poudriere failed, too - the latter because the dependency py-libzfs did not build.

Please let me know if you need any specific log/output. But I guess you have it from your own builds already.

**Comment by fichtner** [comment]
Attached build logs are always appreciated in case this is still a local issue.

**Comment by lattera** [comment]
This is broken due to the port not catching up to upstream FreeBSD's changes to ZFS. This bug should be filed with py-libzfs, maintained by the FreeNAS team: https://github.com/freenas/py-libzfs

**Comment by utrenkner** [comment]
FYI , there already was an open issue related to this problem, so I did not issue one myself. But since nothing happend, I chimed in on Thursday, and py-libzfs was fixed on Friday (the FreeBSD and HardenedBSD ports have been updated already).
