### ISSUE TITLE
Bind911 - could not listen on UDP socket: permission denied

### ISSUE THREAD

**Issue by bryn1u** [HardenedBSD/hardenedbsd-ports#114]
Hello guys,
After few hours bind has stopped listening on interface. I don't know where is the problem.

> Jan  2 18:48:49 dns named[68857]: starting BIND 9.11.2 <id:0a2b929>
> Jan  2 18:48:49 dns named[68857]: running on FreeBSD amd64 11.1-STABLE-HBSD FreeBSD 11.1-STABLE-HBSD #1  bd4021162f1(hardened/11-stable/master): Tue Jan  2 14:56:45 CET 2018     bryn1u@HardenedBSD:/usr/obj/usr/src/sys/Proton
> Jan  2 18:48:49 dns named[68857]: built with '--localstatedir=/var' '--disable-linux-caps' '--disable-symtable' '--with-randomdev=/dev/random' '--with-libxml2=/usr/local' '--with-readline=-L/usr/local/lib -ledit' '--with-dlopen=yes' '--sysconfdir=/usr/local/etc/namedb' '--disable-dnstap' '--disable-filter-aaaa' '--disable-fixed-rrset' '--without-geoip' '--with-idn=/usr/local' '--enable-ipv6' '--with-libjson' '--disable-largefile' '--with-lmdb' '--with-python=/usr/local/bin/python2.7' '--disable-querytrace' '--enable-rpz-nsdname' '--enable-rpz-nsip' 'STD_CDEFINES=-DDIG_SIGCHASE=1' '--enable-threads' '--without-gssapi' '--with-openssl=/usr' '--disable-native-pkcs11' '--with-dlz-filesystem=yes' '--without-gost' '--prefix=/usr/local' '--mandir=/usr/local/man' '--infodir=/usr/local/info/' '--build=amd64-portbld-freebsd11.1' 'build_alias=amd64-portbld-freebsd11.1' 'CC=cc' 'CFLAGS=-O2 -pipe -DHARDENEDBSD -DLIBICONV_PLUG -fPIE -fPIC -fsanitize=safe-stack -fstack-protector-all -isystem /usr/local/include -fno-strict-a
> Jan  2 18:48:49 dns named[68857]: running as: named -u bind -c /usr/local/etc/namedb/named.conf
> Jan  2 18:48:49 dns named[68857]: ----------------------------------------------------
> Jan  2 18:48:49 dns named[68857]: BIND 9 is maintained by Internet Systems Consortium,
> Jan  2 18:48:49 dns named[68857]: Inc. (ISC), a non-profit 501(c)(3) public-benefit
> Jan  2 18:48:49 dns named[68857]: corporation.  Support and training for BIND 9 are
> Jan  2 18:48:49 dns named[68857]: available at https://www.isc.org/support
> Jan  2 18:48:49 dns named[68857]: ----------------------------------------------------
> Jan  2 18:48:49 dns named[68857]: command channel listening on 127.0.0.1#953
> Jan  2 18:48:49 dns named[68857]: all zones loaded
> Jan  2 18:48:49 dns named[68857]: running
> Jan  3 08:51:16 dns named[68857]: not listening on any interfaces
> Jan  3 08:57:18 dns named[68857]: could not listen on UDP socket: permission denied
> Jan  3 08:57:18 dns named[68857]: creating IPv4 interface em0 failed; interface ignored
> Jan  3 08:57:18 dns named[68857]: not listening on any interfaces
> Jan  3 09:48:50 dns named[68857]: could not listen on UDP socket: permission denied
> Jan  3 09:48:50 dns named[68857]: creating IPv4 interface em0 failed; interface ignored
> Jan  3 09:48:50 dns named[68857]: not listening on any interfaces
> Jan  3 10:48:50 dns named[68857]: could not listen on UDP socket: permission denied
> Jan  3 10:48:50 dns named[68857]: creating IPv4 interface em0 failed; interface ignored
> Jan  3 10:48:50 dns named[68857]: not listening on any interfaces
> Jan  3 11:48:50 dns named[68857]: could not listen on UDP socket: permission denied
> Jan  3 11:48:50 dns named[68857]: creating IPv4 interface em0 failed; interface ignored
> Jan  3 11:48:50 dns named[68857]: not listening on any interfaces
> Jan  3 12:48:50 dns named[68857]: could not listen on UDP socket: permission denied
> Jan  3 12:48:50 dns named[68857]: creating IPv4 interface em0 failed; interface ignored
> Jan  3 12:48:50 dns named[68857]: not listening on any interfaces
> Jan  3 13:30:16 dns named[68857]: stopping command channel on 127.0.0.1#953
> Jan  3 13:30:16 dns named[68857]: exiting

It always stops working after few hours and then named listens only on:

> bind     named      79910 21 tcp4   79.137.56.144:53
> bind     named      79910 21 tcp4   79.137.56.144:953

Nothing more. Service is still running but domain is dead. When i restart named everything is back to normal and works well.

There aren't any special security features only default included in HardenedBSD.
Bind is closed in jail. Months ago with exaclly the same settings/config worked great. 
# Edit:
Im wondering why it stops working for example after few hours, no after 1 or 2 or 3 hours ? :(

Someone can help ?

**Comment by lattera** [comment]
Hey @fichtner, I'm wondering if this is due to SafeStack. If he's hitting something that's causing it to misbehave. The SafeStack addition to the bind911 port was added by you on behalf of OPNsense.

Would you have a few moments to dig into this?

**Comment by fichtner** [comment]
Sure. Question is if this was always the case with the port? Can try to disable safestack but I’m not aware of an issue with it in OPNsense.

Likely non-hardened candidate: depletion of file descriptors. That would explain the random but reproducible result...

**Comment by bryn1u** [comment]
And again:

> root@dns:/ # sockstat -4
> USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS      
> bind     named      79910 22 tcp4   79.137.56.144:953     *:*
> root     syslogd    13633 6  udp4   79.137.56.144:514     *:*
> root@dns:/ # 

/var/log/messages

> Jan  3 13:30:16 dns named[79910]: BIND 9 is maintained by Internet Systems Consortium,
> Jan  3 13:30:16 dns named[79910]: Inc. (ISC), a non-profit 501(c)(3) public-benefit 
> Jan  3 13:30:16 dns named[79910]: corporation.  Support and training for BIND 9 are 
> Jan  3 13:30:16 dns named[79910]: available at https://www.isc.org/support
> Jan  3 13:30:16 dns named[79910]: ----------------------------------------------------
> Jan  3 13:30:16 dns named[79910]: command channel listening on 127.0.0.1#953
> Jan  3 13:30:16 dns named[79910]: all zones loaded
> Jan  3 13:30:16 dns named[79910]: running
> Jan  3 21:08:06 dns named[79910]: not listening on any interfaces
> Jan  3 21:08:06 dns named[79910]: could not listen on UDP socket: permission denied
> Jan  3 21:08:06 dns named[79910]: creating IPv4 interface em0 failed; interface ignored
> Jan  3 21:08:06 dns named[79910]: not listening on any interfaces
> Jan  3 21:30:16 dns named[79910]: could not listen on UDP socket: permission denied
> Jan  3 21:30:16 dns named[79910]: creating IPv4 interface em0 failed; interface ignored
> Jan  3 21:30:16 dns named[79910]: not listening on any interfaces

After service named restart:

> root@dns:/ # service named restart
> Stopping named.
> Waiting for PIDS: 79910.
> Starting named.
> root@dns:/ # sockstat -4
> USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS      
> bind     named      62043 21 tcp4   79.137.56.144:53      *:*
> bind     named      62043 22 tcp4   79.137.56.144:953     *:*
> bind     named      62043 512 udp4  79.137.56.144:53      *:*
> bind     named      62043 513 udp4  79.137.56.144:53      *:*
> bind     named      62043 514 udp4  79.137.56.144:53      *:*
> bind     named      62043 515 udp4  79.137.56.144:53      *:*
> bind     named      62043 516 udp4  79.137.56.144:53      *:*
> bind     named      62043 517 udp4  79.137.56.144:53      *:*
> bind     named      62043 518 udp4  79.137.56.144:53      *:*
> root     syslogd    13633 6  udp4   79.137.56.144:514     *:*
> ?        ?          ?     ?  tcp4   79.137.56.144:15695   79.137.56.144:953
> root@dns:/ # 

As you can see working again 

I have recompiled bind911 without SafeStack, and will see what happen.

**Comment by bryn1u** [comment]
Bind911 is still working when SafeStack has been turned off.  Domain is working either, Bind911 is listening on all ports as should be :))

**Comment by fichtner** [comment]
ok, thanks, I'll switch it off then

**Comment by fichtner** [comment]
If the issue should reappear despite safestack being turned off please let us know :)
