### ISSUE TITLE
[SafeStack] Build request for oidentd, mysql57-server, mariadb102-server, pure-ftpd

### ISSUE THREAD

**Issue by bryn1u** [HardenedBSD/hardenedbsd-ports#115]
Hey,

I have been using oidentd, mysql57-server, pure-ftpd, mariadb102-server with enabled SafeStack protector for a long time. All of them are working great and without any problems.

**Comment by noptrix** [comment]
@bryn1u Thanks for this. We will check this and add the safestack flag to those ports.

**Comment by noptrix** [comment]
@bryn1u added safestack to oidentd and pure-ftpd. Since the mysql-server and maria-server port install a .so files, which other ports depend on, SafeStack will not be added for these ports
