### ISSUE TITLE
[SafeStack] - Nginx `__safestack_unsafe_stack_ptr' follow

### ISSUE THREAD

**Issue by bryn1u** [HardenedBSD/hardenedbsd-ports#116]
> Hello,
> 
> objs/src/core/nginx.o: In function `main':
> src/core/nginx.c:(.text+0x19): undefined reference to `__safestack_unsafe_stack_ptr'
> src/core/nginx.c:(.text+0x3d4): undefined reference to `__safestack_unsafe_stack_ptr'
> src/core/nginx.c:(.text+0x475): undefined reference to `__safestack_unsafe_stack_ptr'
> src/core/nginx.c:(.text+0x541): undefined reference to `__safestack_unsafe_stack_ptr'
> src/core/nginx.c:(.text+0x811): undefined reference to `__safestack_unsafe_stack_ptr'
> objs/src/core/nginx.o:src/core/nginx.c:(.text+0x9db): more undefined references to `__safestack_unsafe_stack_ptr' follow
> cc: error: linker command failed with exit code 1 (use -v to see invocation)
> *** Error code 1
> 
> Stop.
> make[2]: stopped in /usr/ports/www/nginx/work/nginx-1.12.2
> *** Error code 1
> 
> Stop.
> make[1]: stopped in /usr/ports/www/nginx/work/nginx-1.12.2
> *** Error code 1
> 
> Stop.
> make: stopped in /usr/ports/www/nginx
> root@proton:/usr/ports/www/nginx # 
>

**Comment by lattera** [comment]
HardenedBSD doesn't have SafeStack enabled for nginx.
