### ISSUE TITLE
[SafeStack] Enable for editors/joe

### ISSUE THREAD

**Issue by kaskasbarakas** [HardenedBSD/hardenedbsd-ports#117]
I have been using Joe's Own Editor with safestack enabled for awhile.
Compiles fine with SafeStack and runs fine.

**Comment by lattera** [comment]
Thank you for reporting this! I'm going to assign this ticket to @noptrix and let him do his magic.

**Comment by noptrix** [comment]
@kaskasbarakas ok. thanks for this. we will add the safestack flag to joe.

**Comment by noptrix** [comment]
SafeStack added for editor/joe (https://github.com/HardenedBSD/hardenedbsd-ports/commit/28473acfb0373dbcfdfe34f99e5e2bf7b2f433cf) and editor/joe2 (https://github.com/HardenedBSD/hardenedbsd-ports/commit/0b67dabd87c6aaa46a5f712db6d91d5cdbc56c21)
