### ISSUE TITLE
[SafeStack] some more ports

### ISSUE THREAD

**Issue by kaskasbarakas** [HardenedBSD/hardenedbsd-ports#118]
You can turn on safestack for security/keepassxc and games/openttd and also for graphics/xpdf.
They all work and compile without issue.

**Comment by kaskasbarakas** [comment]
print/qpdfview also works flawless with safestack

**Comment by noptrix** [comment]
@kaskasbarakas thanks for this. I will take a look and SS flags to those ports you mentioned

**Comment by noptrix** [comment]
added: openttd (https://github.com/HardenedBSD/hardenedbsd-ports/commit/6e4bc2efb7716c460d3d494fbcbd45dc372172ed), xpdf3 (https://github.com/HardenedBSD/hardenedbsd-ports/commit/8215abd5969d45d86992cb48cd99f5e3959943b6) and xpdf4 (https://github.com/HardenedBSD/hardenedbsd-ports/commit/811f48a0f0763f64994cdc322e179963303dc9e4)

Not sure about 'keepassxc' though, as it creates a .so file. @lattera What we can do with 'security/keepassxc'?

**Comment by lattera** [comment]
Search for the .so file in plists of other ports. The FreshPorts website has a nice little plist search function. If no other port uses the .so file, go ahead and add SafeStack to that port.

Let me know if that doesn't make sense.

**Comment by noptrix** [comment]
Nope, absolutely fine. This was the approach I had in my mind. :)

**Comment by noptrix** [comment]
added: keepassxc (https://github.com/HardenedBSD/hardenedbsd-ports/commit/0ea65353a1da081e14e43a466feeea8dd6c0a1dc)
