### ISSUE TITLE
[CFI] Add CFI to net-im/mcabber

### ISSUE THREAD

**Issue by noptrix** [HardenedBSD/hardenedbsd-ports#119]
I've been using mcabber with CFI enabled without any problems.

**Comment by lattera** [comment]
It seems net-im/mcabber installs .so files. Can you verify if there are any ports that consume them?

**Comment by noptrix** [comment]
@lattera haven't found any references for: 
`lib/mcabber/libbeep.so
lib/mcabber/libfifo.so
lib/mcabber/liburlregex.so
lib/mcabber/libxttitle.so
`
So feel free to add CFI :)

**Comment by lattera** [comment]
Will do. Thanks!
