### ISSUE TITLE
node-v9.6.1 - (core dumped) Received signal 11 SEGV_ACCERR 1fafde3a1920

### ISSUE THREAD

**Issue by bryn1u** [HardenedBSD/hardenedbsd-ports#122]
Hello everyone,

Im trying to install node from ports with simple command based on default config:
`make install clean`
After while im getting error. 
> Received signal 11 SEGV_ACCERR 1fafde3a1920
> 
> ==== C stack trace ===============================
> 
>  [0x02a6558cf8d4]
>  [0x058fdd049934]
>  [0x058fdd048ecf]
> [end of stack trace]
> gmake[2]: *** [deps/v8/src/v8_snapshot.target.mk:13: /usr/ports/www/node/work/node-v9.6.1/out/Release/obj.target/v8_snapshot/geni/snapshot.cc] Segmentation fault (core dumped)
> gmake[2]: *** Waiting for unfinished jobs....
> rm 471bf70714bde4fa46071578f46780471632f5f4.intermediate
> gmake[1]: *** [Makefile:90: node] Error 2
> gmake[1]: Leaving directory '/usr/ports/www/node/work/node-v9.6.1'
> ===> Compilation failed unexpectedly.
> Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
> the maintainer.
> *** Error code 1
> 
> Stop.
> make: stopped in /usr/ports/www/node

Output `secadm show`

> +3: pax /usr/local/bin/node mp

Dmesg on host shows:

> [272505] pid 51209 (mksnapshot), uid 0: exited on signal 11 (core dumped)
> [274660] pid 80911 (mksnapshot), uid 0: exited on signal 11 (core dumped)
>

**Comment by lattera** [comment]
Did you set the `hardening.pax.pageexec.status` and `hardening.pax.mprotect.status` sysctl nodes to 1 before attempting the build?

**Comment by bryn1u** [comment]
You are right. Works fine for me. Thank you for your help.
