### ISSUE TITLE
[SAFESTACK] Add SafeStack to sysutils/pciutils

### ISSUE THREAD

**Issue by pkubaj** [HardenedBSD/hardenedbsd-ports#124]
Compiles fine here.

**Comment by lattera** [comment]
I'm unable to find this port in the ports tree. Can you verify it still exists?

**Comment by pkubaj** [comment]
Sorry, I meant sysutils/pciutils.

**Comment by lattera** [comment]
I've also added, after testing, CFI for those on 12-CURRENT/amd64. Thanks!
