### ISSUE TITLE
Add SAFESTACK and CFI to shells/oksh

### ISSUE THREAD

**Issue by pkubaj** [HardenedBSD/hardenedbsd-ports#129]
The port compiles and works fine with both.

**Comment by pkubaj** [comment]
Fixed.

**Comment by lattera** [comment]
@pkubaj Can you reference the issue number in your commit message? For example, a template commit message would look like this:

```
HBSD: One liner header

More detailed explanation, if needed.

gitub-issue:    #129
Signed-off-by:  your.email@here.com
````
