### ISSUE TITLE
Remove security/luasec/files

### ISSUE THREAD

**Issue by pkubaj** [HardenedBSD/hardenedbsd-ports#13]
The only patch in files/ breaks patch step. The port fails to build anyway, but I've submitted a PR about it:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=210462

If you wish to, you can create this patch to fix the issue until it's commited to FreeBSD ports:
--- files/patch-src_ssl.c	(revision 0)
+++ files/patch-src_ssl.c	(working copy)
@@ -0,0 +1,10 @@ 
+--- src/ssl.c.orig	2016-07-12 14:52:21 UTC
++++ src/ssl.c
+@@ -14,6 +14,7 @@
+ #include <Winsock2.h>
+ #endif
+ 
++#include <openssl/comp.h>
+ #include <openssl/ssl.h>
+ #include <openssl/x509v3.h>
+ #include <openssl/x509_vfy.h>

**Comment by Sp1l** [comment]
Duplicate of #16
