### ISSUE TITLE
[LibreSSL] build failure for lang/rust

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedbsd-ports#135]
Build log attached. Given that www/firefox depends on lang/rust, please consider this as high priority.

[2018-04-11-rust-1.24.1.log.txt](https://github.com/HardenedBSD/hardenedbsd-ports/files/1900398/2018-04-11-rust-1.24.1.log.txt)

**Comment by lattera** [comment]
@Sp1l, can you look at incorporating the patch from this bug ticket? https://github.com/sfackler/rust-openssl/issues/883

**Comment by pkubaj** [comment]
There's also a PR in FreeBSD Bugzilla: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=226955 with a ready to commit patch.
