### ISSUE TITLE
Gnome3 fails to compile on fresh HBSD 11 install

### ISSUE THREAD

**Issue by uranther** [HardenedBSD/hardenedbsd-ports#138]
cd /usr/ports/x11/gnome3
    make install clean

I get a number of issues with packages that are Python 2.7-only trying to compile with Python 3.6. If I install these dependencies separately, I am able to continue the Gnome3 build.

```
textproc/itstool
devel/pydbus-common
audio/libsndfile -- make DISABLE_VULNERABILITIES=yes install clean
textproc/ibus
devel/libevent
devel/zziplib
www/webkit2-gtk3
net-im/telepathy-glib
```

However, building `net/samba46` seemed to trigger a LibreSSL-related error in `net/openldap24-client` and now I don't know how to continue the Gnome3 build.

I can provide more details as needed, and I will fetch the latest ports repo to test any updates.

**Comment by lattera** [comment]
Thank you very much for the bug report! I've assigned @Sp1l to help you resolve the LibreSSL-related issues.

**Comment by pkubaj** [comment]
I just built `net/openldap24-client` against LibreSSL without any additional patches, so I'm closing this.
