### ISSUE TITLE
[SafeStack] for Dovecot & Postfix 

### ISSUE THREAD

**Issue by bryn1u** [HardenedBSD/hardenedbsd-ports#141]
Hello guys,

Could you kindly add SafeStack for dovecot "/usr/ports/mail/dovecot"  and postfix "/usr/ports/mail/postfix" to the package/pkg. Im using it and working good. I think it's important enough because of server hosting purpose where many people using it.

Thank you, :)

**Comment by lattera** [comment]
@noptrix, if you have time, could you look into this? If not, I can take a look sometime after mid-June.

**Comment by noptrix** [comment]
@lattera yep, it's fine. i can work on this by next week.

**Comment by pkubaj** [comment]
It's applied now for Postfix, Dovecot throws errors, so no SafeStack for it:
==80815==Sanitizer CHECK failed: /usr/src/contrib/compiler-rt/lib/sanitizer_common/sanitizer_common.cc:55 ((0 && "unable to mmap")) != (0) (0, 0)
==35409==ERROR: SanitizerTool failed to allocate 0x40001000 (1073745920) bytes of unsafe_stack_alloc (error code: 12)

**Comment by bryn1u** [comment]
Okey, thank you :)

śr., 18 lip 2018 o 11:35 pkubaj <notifications@github.com> napisał(a):
