### ISSUE TITLE
Compile error for net/qt5-network

### ISSUE THREAD

**Issue by utrenkner** [HardenedBSD/hardenedbsd-ports#144]
Because the latest HardenedBSD-packages for 11-STABLE did not include a working lumina desktop, I tried building it myself with Poudriere. But the built stops at net/qt5-network with the following log message:
```
In file included from ssl/qsslsocket_openssl_symbols_p.h:220:
ssl/qsslsocket_openssl11_symbols_p.h:96:22: error: unknown type name 'OPENSSL_STACK'
int q_OPENSSL_sk_num(OPENSSL_STACK *a);
```
Here is poudriere's full [build log for qt5-network](https://gist.github.com/utrenkner/11240bf5d0387a76218ab7482185f3e2).

**Comment by lattera** [comment]
Thank you very much for the bug report! I'll assign this to @Sp1l.

**Comment by Sp1l** [comment]
Hi Uwe,

Do you have commit 30d270ba4e318e2ecc7afc0f0be1be4ff77fc08b in your tree? That should fix the build.

**Comment by utrenkner** [comment]
Hi Bernard, 

I think so. But just to be sure, I tried for a third time, now. I always updated the ports tree via a ``git pull``. This time I even checked that the indicated commit was present. But still, the build of net/qt5-network fails with the same error message.

This is on the latest 11-STABLE version available via hbsd-update, with the latest ports, build with poudriere.

**Comment by utrenkner** [comment]
As suggested by @Sp1l on the mailing list, I just compared the [TrueOS port of qt5-network](https://github.com/trueos/trueos-ports/tree/trueos-master/net/qt5-network) with [HardenedBSD's version](https://github.com/HardenedBSD/hardenedbsd-ports/tree/master/net/qt5-network). Zero difference, they are identical! Thus the root of the problem must lie somewhere else.

**Comment by Sp1l** [comment]
There are slight differences in OpenSSL vs LibreSSL with regards to STACKS.
Not sure what's going on here.

**Comment by utrenkner** [comment]
Do you have any suggestion on how to proceed? Even though I could work with another DE or window manager, I absolutely need qt5-network, because I store most of my passwords in [security/keepassxc](https://github.com/HardenedBSD/hardenedbsd-ports/tree/master/security/keepassxc), which depends on this library.

**Comment by utrenkner** [comment]
I just updated my Laptop to the new HardenedBSD 11-STABLE version with OpenSSL. qt5-network is now again in the official repo and *my* problem is solved. 

I therefore close this issue, even though the original problem of qt5-network with LibreSSL is not solved.

Thanks.
