### ISSUE TITLE
Poudriere stops because of missing/mismatching version numbers

### ISSUE THREAD

**Issue by utrenkner** [HardenedBSD/hardenedbsd-ports#151]
I have a problem with poudriere on the very latest 11-STABLE:

When I try a bulk build, it stops with this error
```
make: "/usr/ports/Mk/bsd.port.mk" line 1211: UNAME_r () and OSVERSION (1102501) do not agree on major version number.
```
I think I had a similar issue before and somehow fixed that... but I forgot how. How are you building packages for HBSD?

Background on the system: It is a DigitalOcean droplet converted today from FreeBSD 11.2-RELEASE to HardenedBSD 11-STABLE. The poudriere jail was also updated to the latest with hbsd-update.

I tried setting the OSRELEASE in a jail-specific make.conf. That helped start the build. But in the end the build of pkg already failed because 
```
make: don't know how to make 1102501. Stop
```

**Comment by lattera** [comment]
I've never run into that.

Here is some horribly-written documentation on how I've set up Poudriere before: https://gist.github.com/22e4f9d2c056b7fbf62adcdf82cd4a50

**Comment by utrenkner** [comment]
Thank you, @lattera. The general setup is ok. It is just the version check that is not working correctly.

With even more web searching I found a combination of configuration directives that work. I have not yet tried to trim it further down, as I just want to build a few ports for tonight's migration of our production server from 11-STABLE with LibreSSL to 11-STABLE with OpenSSL.

This is what works for me at the moment:
/usr/local/etc/poudriere.d/<jailname>-<portcollection-name>-make.conf
```
 UNAME_ENV+=     UNAME_s=FreeBSD                                                                                                                                                                                   
 UNAME_ENV+=     UNAME_r=11.2-RELEASE                                                                                                                                                                              
 UNAME_ENV+=     UNAME_v="${UNAME_s} ${UNAME_r}"                                                                                                                                                                   
 .MAKEFLAGS:     ${UNAME_ENV}                                                                                                                                                                                      
 MAKE_ENV+=      ${UNAME_ENV}                                                                                                                                                                                      
 CONFIGURE_ENV+= ${UNAME_ENV}                                                                                                                                                                                      
 SCRIPTS_ENV+=   ${UNAME_ENV} 
```
/usr/local/etc/poudriere.d/jails/<jailname>/version
```
11.2-RELEASE
```
I intend to publish a Howto (or Gist) for turning a DigitalOcean VPS ("droplet") with FreeBSD into a build machine running the latest HardenedBSD with poudriere. 

However, I will wait for your re-work of ``hbsd-update``, especially for what concerns the version-check. Both, turning FreeBSD into HardenedBSD, and setting up the initial Poudriere jail will become simpler, once #303 is fixed. At the moment, I always have to pre-fill the target (boot environment or jail directory) with the content of base.txz, before using ``hbsd-update -r``.

**Comment by utrenkner** [comment]
I am closing this issue, as I found the solution mentioned above. The one port I needed to build (www/h2o.... which was bug-fixed just hours after the latest package build) was built successfully and is deployed on the freshly upgraded, OpenSSL-based 11-STABLE server.
