### ISSUE TITLE
[SafeStack] Mariadb 10.1.34 failure when built with safestack enabled.

### ISSUE THREAD

**Issue by dmilith** [HardenedBSD/hardenedbsd-ports#156]
Long story short:

My system: 11.2 (11-STABLE)
Arch: x86_64
Mariadb: 10.1.34

Invoking mysqld ends with:

```
2018-07-30 14:33:45 4156920258560 [Note] /Software/Mariadb/bin/mysqld (mysqld 10.1.34-MariaDB) starting as process 54321 ...
==54321==Sanitizer CHECK failed: /λ/src/11/contrib/compiler-rt/lib/safestack/safestack.cc:195 (((size & (kStackAlign - 1)))) == ((0)) (4, 0)
```

**Comment by bryn1u** [comment]
MariaDB can't be build with SafeStack. The same Mysql.

pon., 30 lip 2018 o 16:43 Daniel (dmilith) Dettlaff <
notifications@github.com> napisał(a):

**Comment by lattera** [comment]
Note: @dmilith enabled SafeStack himself for MariaDB. I was not aware of that when I asked him to open this ticket. I'm closing it out because HardenedBSD doesn't have SafeStack enabled by default for MariaDB.
