### ISSUE TITLE
security/luasec build failure

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedbsd-ports#16]
Build fails on the hardened/current/master branch. Since it fails in the patch stage, it ought to also fail in the hardened/current/master-libressl branch, too.

[2016-07-20-lua51-luasec-0.5.1.log.txt](https://github.com/HardenedBSD/hardenedbsd-ports/files/374506/2016-07-20-lua51-luasec-0.5.1.log.txt)

**Comment by Sp1l** [comment]
Port was updated to 0.5.1, patch is now included upstream. New issue popped up with SSL Compression, fixed by f4e53d3f63eab8616e9b8bfa39c09872e96edbe8
