### ISSUE TITLE
[SafeStack]  Add SafeStack for BitchX 

### ISSUE THREAD

**Issue by bryn1u** [HardenedBSD/hardenedbsd-ports#161]
Hello,

Can SafeStack be added to Bitchx irc session ?

 /usr/ports/chinese/bitchx

**Comment by pkubaj** [comment]
Have you tested that bitchx works with SafeStack?

**Comment by bryn1u** [comment]
Im using it and users on server use it too to ircnet.

**Comment by pkubaj** [comment]
Fixed in https://github.com/HardenedBSD/hardenedbsd-ports/commit/82316c9ce13b8bf50f84c17071a3fdc05a27c9d6.
