### ISSUE TITLE
[SafeStack] Add SafeStack for mc  (Midnight Commander)

### ISSUE THREAD

**Issue by bryn1u** [HardenedBSD/hardenedbsd-ports#162]
Hello,

Can SafeStack be added to mc (Midnight Commander) software ?

/usr/ports/misc/mc

**Comment by pkubaj** [comment]
It can, but does it work? Have you tested mc built with SafeStack?

**Comment by bryn1u** [comment]
Im using it and i haven't had any issues.

**Comment by pkubaj** [comment]
Fixed in https://github.com/HardenedBSD/hardenedbsd-ports/commit/82316c9ce13b8bf50f84c17071a3fdc05a27c9d6.
