### ISSUE TITLE
[LibreSSL] Build failure for devel/qca

### ISSUE THREAD

**Issue by Sp1l** [HardenedBSD/hardenedbsd-ports#163]
Recently, patches were added to devel/qca to make it work with OpenSSL 1.1.1
These break building with LibreSSL.

Looks like a simple job of adding `&& !defined(LIBRESSL_VERSION_NUMBER)` in the newly added patches in http://svnweb.freebsd.org/changeset/ports/481850

**Comment by pkubaj** [comment]
Fixed.
