### ISSUE TITLE
[irc/ircd-ratbox-devel] LibreSSL build error

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedbsd-ports#17]
Log attached.

[ircd-ratbox-devel-3.0.7_3.log.txt](https://github.com/HardenedBSD/hardenedbsd-ports/files/768456/ircd-ratbox-devel-3.0.7_3.log.txt)

**Comment by Sp1l** [comment]
Ignore, regular ircd-ratbox port is newer than -devel
