### ISSUE TITLE
cannot build pkg (maybe all other ports also) segfault on install phase

### ISSUE THREAD

**Issue by chrcoluk** [HardenedBSD/hardenedbsd-ports#172]
So updated from hbsd11 to latest 12 stable branch.

I am trying to reinstall pkg port, and it compailes fine, but then I see this.

This is using the default pre selected port options.  Also I recompiled all of world without reptoline incase that was the problem.

`===>   Installing ldconfig configuration file
===>  Installing for pkg-1.15.10
===>   Registering installation for pkg-1.15.10
*** Signal 11

Stop.
make[3]: stopped in /usr/ports/ports-mgmt/pkg
*** Error code 1

Stop.
make[2]: stopped in /usr/ports/ports-mgmt/pkg
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/ports-mgmt/pkg
*** Error code 1

Stop.
make: stopped in /usr/ports/ports-mgmt/pkg`

**Comment by chrcoluk** [comment]
I found an issue on here posted in 2018 mentioning pkg-static so I navigated into the stage folder, the compiled plkg runs fine but pkg-static does indeed segfault, even if I disable all hardening flags for the port it still crashes.

given pkg is required for the entire ports tree does this mean ports are unusable right now or is there a workaround?

**Comment by hbsd-robot0** [comment]
What version of HardenedBSD are you on now? If you're on 12, what steps did
you perform to do the upgrade?

**Comment by chrcoluk** [comment]
It was a slog, as the older build didnt want to buildworld, it was failing on the old linker using /usr/bin/ld instead of using the bootstrap version, so the OS was updated by hbsd-update, and then I did a buildworld after just to make sure it compiles with new compiler in place.

so

hbsd-update (with ,manual editing of adding ntpd and tests user to passwd, as hbsd-update has no pre mergemaster)

then after it was already updated, I grabbed latest 12. of github.

make -j4 buildworld
make -j4 buildkernel
make installworld
make installkernel
mergemaster

and I also did make-delete-old (but not yet for libraries until I recompile ports).

**Comment by chrcoluk** [comment]
Interesting make deinstall reinstall was not actually removing the installed 'pkg'.

After doing pkg delete -f pkg, it installs fine.

**Comment by chrcoluk** [comment]
Ok I understand what was going on now, the PIE option makes it fail, the first time I tried to install the port it half installed it, which will make all subsequent attempts fail regardless of flag unless it is manually removed, and the flag that causes the broken binary is PIE (disabled by default).

**Comment by lattera** [comment]
> I guess this raises a new question, if a default gets changed, will it only get picked up with a rmconfig?

Yeah, that's an issue inherited from upstream FreeBSD.

You'll want to note that HardenedBSD no longer uses github as the source of truth. You'll want to file bugs at HardenedBSD's self-hosted git server: https://git-01.md.hardenedbsd.org/

Subscribing to the HardenedBSD users mailing list will help easily keep you informed of changes and progress of the HardenedBSD project.

**Comment by chrcoluk** [comment]
Ok I will do so, thanks, will also close this issue.
