### ISSUE TITLE
[irc/irssi-xmpp] LibreSSL build error

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedbsd-ports#22]
Log attached.

[irssi-xmpp-0.53_1.log.txt](https://github.com/HardenedBSD/hardenedbsd-ports/files/768463/irssi-xmpp-0.53_1.log.txt)

**Comment by Sp1l** [comment]
Closed by ccabc7c976879d1d5d55196c673b6b44e8a8fc6e
