### ISSUE TITLE
python fails to build on 10-stable: undefined reference to `Py_Main`

### ISSUE THREAD

**Issue by Scarletts** [HardenedBSD/hardenedbsd-ports#3]
python27
-------------

```
cc -lpthread -Wl,-rpath,/usr/local/lib -Wl,-rpath=/usr/lib:/usr/local/lib -pie -Wl,-z,relro -Wl,-z,now -fstack-protector -Wl,--export-dynamic -o python Modules/python.o -L. -lpython2.7 -L/usr/local/lib -lintl -lutil -lm
Modules/python.o: In function `main`:
./Modules/python.c:(.text+0x6b): undefined reference to `Py_Main`
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```

python34
--------------

```
cc -lpthread -Wl,-rpath,/usr/local/lib -Wl,-rpath=/usr/lib:/usr/local/lib -pie -Wl,-z,relro -Wl,-z,now -fstack-protector -Wl,--export-dynamic -o python Modules/python.o -L. -lpython3.4 -lintl -L/usr/local/lib -lintl -lutil -lm
Modules/python.o: In function `main`:
./Modules/python.c:(.text+0xbc): undefined reference to `_PyMem_RawStrdup`
./Modules/python.c:(.text+0xf7): undefined reference to `_Py_char2wchar`
./Modules/python.c:(.text+0x147): undefined reference to `Py_Main`
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```

Using latest published build and latest ports tree checkout.

**Comment by lattera** [comment]
This could be because of us building python with the PIE flag. Can you remove the pie USES flag from the port's Makefile and try again?

**Comment by Scarletts** [comment]
$ python2.7
    Python 2.7.10 (default, Nov 12 2015, 09:57:05)
    [GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)] on freebsd10
    Type "help", "copyright", "credits" or "license" for more information.
    >>> 

As far as I can tell, removing the pie USES flag allows Python to build.

Sorry for taking almost two weeks to respond :(

Might it be worth disabling the [PYMALLOC](http://docs.activestate.com/activepython/3.2/whatsnew/2.3/section-pymalloc.html) option by default? It may allow Python to benefit from security improvements to the system allocator.

**Comment by Scarletts** [comment]
pie also seems to be a problem with multimedia/ffmpeg.

**Comment by lattera** [comment]
No worries about the time delay. We're all busy folk. I'll go ahead and fully disable my pie USES flag on 10-STABLE. I'll take a look at the PYMALLOC option. Can you open a new bug report for that since it's technically a separate bug than what we're discussing here? That way, I can also give proper attribution to you in the commit log. Thanks!
