### ISSUE TITLE
emulators/virtualbox-ose: fix check-sanity when building in jail

### ISSUE THREAD

**Issue by pkubaj** [HardenedBSD/hardenedbsd-ports#39]
This patch fixes check-sanity target in jails.
[virtualbox-ose.txt](https://github.com/HardenedBSD/hardenedbsd-ports/files/813022/virtualbox-ose.txt)

**Comment by lattera** [comment]
I'll work on this tonight. Thanks!

**Comment by lattera** [comment]
Merged in. Thanks a lot!
