### ISSUE TITLE
[www/firefox] Build fail...

### ISSUE THREAD

**Issue by jamespanda** [HardenedBSD/hardenedbsd-ports#40]
The same issue with the default options...

[firefox-52.0_3,1-log.txt](https://github.com/HardenedBSD/hardenedbsd-ports/files/828880/firefox-52.0_3.1-log.txt)

**Comment by lattera** [comment]
Do you have the hardening.pax.pageexec.status and hardening.pax.mprotect.status sysctl nodes set to 1? Firefox (and even its build process) doesn't like PaX NOEXEC (aka, strict W^X).

**Comment by jamespanda** [comment]
hardening.pax.mprotect.status: 2
hardening.pax.pageexec.status: 2

**Comment by jamespanda** [comment]
i try again...thanks

**Comment by jamespanda** [comment]
it seemed that the two values must be disable?

**Comment by lattera** [comment]
In this case, a value of 1 for those sysctl nodes means that applications must be opted in to NOEXEC rather than opted out.

**Comment by jamespanda** [comment]
thank you for the description
I just see...
hardening.pax.mprotect.status: Restrictions status: 0 - disabled, 1 - opt-in,  2 - opt-out, 3 - force enabled
hardening.pax.pageexec.status: Restrictions status: 0 - disabled, 1 - opt-in,  2 - opt-out, 3 - force enabled

**Comment by jamespanda** [comment]
tuned both to 0 and failed again...

**Comment by lattera** [comment]
Can you post the new log?

**Comment by jamespanda** [comment]
let me build again...
not used to logging...

**Comment by jamespanda** [comment]
[firefox-52.0_3,1-log2.txt](https://github.com/HardenedBSD/hardenedbsd-ports/files/829388/firefox-52.0_3.1-log2.txt)

it seems that default options make it work...(no safestatck && no cfi)
thanks

**Comment by lattera** [comment]
Yup. SafeStack and CFI cannot be enabled for Firefox.

Note that CFI shouldn't really be enabled for any ports, yet. It's simply there as a toy for those who are on 12-CURRENT/amd64.

**Comment by lattera** [comment]
Is this issue resolved? If so, we can close it.

**Comment by jamespanda** [comment]
yes...all things fine
