### ISSUE TITLE
Set "WITH_SSP_PORTS=yes" by default in order to enable -fstack-protector for most ports

### ISSUE THREAD

**Issue by vrijn** [HardenedBSD/hardenedbsd-ports#45]
C.f. "man ports":
WITH_SSP_PORTS ---    (bool) If set, enables -fstack-protector for most ports.

**Comment by vrijn** [comment]
I think it's also necessary to set 
sysctl security.bsd.stack_guard_page=1
for SSP to have any effect.

(But I'm not 100% sure at the moment.)

**Comment by lattera** [comment]
The `security.bsd.stack_guard_page` sysctl node is set to 1 by default in HardenedBSD.

**Comment by lattera** [comment]
Looks like SSP is enabled by default for the whole ports tree. Note that individual ports can define SSP_UNSAFE, which will cause the port to opt-out of SSP.
