### ISSUE TITLE
Where can I see the compile options used for each port?

### ISSUE THREAD

**Issue by utrenkner** [HardenedBSD/hardenedbsd-ports#48]
I never tried to change the options when I used FreeBSD. But now I would like to compile a newer version of www/h2o from sources and would like to know, what compiler options are used with the the port version of www/h2o. I would like to use the same.

Plus: Does it make sense to try SafeStack on this port? Or have you tested it already and it did not work? How does it usually show, if SafeStack breaks a port - is it immediately visible?

**Comment by pkubaj** [comment]
Just run `make showconfig` inside the port directory. You can also check in /var/db/ports.

**Comment by lattera** [comment]
Note that the issues system in GitHub isn't meant to be used as tech support. Please refer to the HardenedBSD Handbook for answers to general questions.

Regarding SafeStack. If you find a port that does not have SafeStack enabled for it, and you have manually enabled SafeStack and find that it works, please open a ticket letting us know. We definitely need help identifying ports that work with SafeStack.

**Comment by utrenkner** [comment]
I apologize for putting this question here. But because I could find no HardenedBSD forum and because other projects use GH issues like a forum, I put my question here. 

I understand that this is not how you do it and I will follow-up on the mailing list.
