### ISSUE TITLE
PIE and RELRO not been used for ports

### ISSUE THREAD

**Issue by chrcoluk** [HardenedBSD/hardenedbsd-ports#5]
Sorry I posted a bug report in the wrong github, will close the other one.

I observed I have no RELRO and PIE on port binaries.  It did work if I modified the make.conf to add the flags.

I then found your blog post and went to this url

https://github.com/HardenedBSD/hardenedbsd-ports/commit/930073807710bb8299896c9822e6a4be77e53501

This shows port Makefiles where the lines should exist but in my port Makefiles the lines are missing.

I am using 11-STABLE

FreeBSD shiva.chrysalisnet.org 11.0-STABLE-HBSD FreeBSD 11.0-STABLE-HBSD #0 646da84b22f(hardened/11-stable/master)-dirty:

**Comment by lattera** [comment]
Which port did you install that didn't have PIE enabled?

**Comment by lattera** [comment]
And what ports repo did you use? If you're missing lines in Makefiles, then chances are, you're using the wrong ports repo.

**Comment by chrcoluk** [comment]
I didnt specify a ports repo which I suspect is the problem, I searched but could not find any documentation on port repo configuration.

portsnap.conf is fetching from FreeBSD's repo.

If I am not supposed to use portsnap or am supposed to reconfigure portsnap.conf, please advise how thank you.

In terms of the ports I tested many, nano I did most of my testing on tho as it is quick to compile.  But the lines in the Makefile are missing, so the issue seems to be using the wrong repo to download prt's files.

**Comment by lattera** [comment]
We've disabled portsnap in HardenedBSD for a reason: we don't support it.

You'll want to use HardenedBSD's ports repo. Here's a link that will show you how to download our ports repo:

https://github.com/HardenedBSD/hardenedBSD/blob/hardened/current/master/UPDATING-HardenedBSD#L243

**Comment by chrcoluk** [comment]
Than you, wiping the local ports tree now so can get the proper files :)
