### ISSUE TITLE
security/openconnect: fix build with LibreSSL

### ISSUE THREAD

**Issue by pkubaj** [HardenedBSD/hardenedbsd-ports#51]
The issue has been reported upstream and the patch has been committed in http://git.infradead.org/users/dwmw2/openconnect.git/commitdiff/69793ae0c1b3b6cb2e4baecc224ea714707ac329?hp=539e3ee70a520b879226a80c60ad9b1b9f344bf2

Patch originally taken from Gentoo LibreSSL overlay.

**Comment by Sp1l** [comment]
From: gentoo/libressl@dcda666425fb287aea66724dfd5e52514e9099e7
