### ISSUE TITLE
Bash issue compile from ports.

### ISSUE THREAD

**Issue by bryn1u** [HardenedBSD/hardenedbsd-ports#55]
Hello gusy,

I've been trying so many times and i cant compile bash from ports:

> See `config.log' for more details
> ===>  Script "configure" failed unexpectedly.
> Please report the problem to ehaupt@FreeBSD.org [maintainer] and attach the
> "/usr/ports/shells/bash/work/bash-4.4/config.log" including the output of the
> failure of your make command. Also, it might be a good idea to provide an
> overview of all packages installed on your system (e.g. a
> /usr/local/sbin/pkg-static info -g -Ea).
> *** Error code 1

/usr/ports/shells/bash/work/bash-4.4/config.log

> 
> #define HAVE_MBSTATE_T 1
> #define HAVE_ISWLOWER 1
> #define HAVE_ISWUPPER 1
> #define HAVE_TOWLOWER 1
> #define HAVE_TOWUPPER 1
> #define HAVE_ISWCTYPE 1
> #define HAVE_LANGINFO_CODESET 1
> #define HAVE_WCHAR_T 1
> #define HAVE_WCTYPE_T 1
> #define HAVE_WINT_T 1
> #define HAVE_LOCALE_CHARSET 1
> #define HAVE_DECL_SYS_SIGLIST 1
> #define GETGROUPS_T int
> #define HAVE_UINTPTR_T 1
> #define HAVE_LONG_LONG 1
> #define HAVE_UNSIGNED_LONG_LONG 1
> #define RETSIGTYPE void
> 
> configure: exit 77
> root@proton:/usr/ports/shells/bash # 
Doesnt matter if its compile with/without hardened flags always the same mistake.  From pkg works good and freebsd either

**Comment by chrcoluk** [comment]
this is due to static and PIE both been enabled, also affects ccache.

https://github.com/HardenedBSD/hardenedBSD/issues/274

sorry about posting the above in wrong place.

**Comment by fichtner** [comment]
@chrcoluk I fixed ccache by avoiding hardening on "-static" port suffixes

this doesn't work for bash so hardening was backed out completely. I'll revisit this tomorrow.

**Comment by fichtner** [comment]
not the pretties thing in the world, but now STATIC on bash simply undoes hardening. At least this way we still have hardening for the dynamic bash. :)
