### ISSUE TITLE
Perl - 5.24 compile issue 

### ISSUE THREAD

**Issue by bryn1u** [HardenedBSD/hardenedbsd-ports#56]
Hello,
I have a compile problem with perl-5.24 from ports.

> 
> caretx.o mpdtrace/dquote.o mpdtrace/time64.o mpdtrace/miniperlmain.o dtrace_mini.o -lpthread -lm -lcrypt -lutil
> mpdtrace/opmini.o: In function `Perl_op_clear':
> opmini.c:(.text+0xb3a): undefined reference to `__safestack_unsafe_stack_ptr'
> opmini.c:(.text+0xddd): undefined reference to `__safestack_unsafe_stack_ptr'
> mpdtrace/opmini.o: In function `Perl_custom_op_get_field':
> opmini.c:(.text+0x166d): undefined reference to `__safestack_unsafe_stack_ptr'
> opmini.c:(.text+0x18ee): undefined reference to `__safestack_unsafe_stack_ptr'
> mpdtrace/opmini.o: In function `Perl_load_module':
> opmini.c:(.text+0x4cab): undefined reference to `__safestack_unsafe_stack_ptr'
> mpdtrace/opmini.o:opmini.c:(.text+0x4dbd): more undefined references to `__safestack_unsafe_stack_ptr' follow
> cc: error: linker command failed with exit code 1 (use -v to see invocation)
> *** Error code 1
> 
> Stop.
> make[2]: stopped in /usr/ports/lang/perl5.24/work/perl-5.24.1
> *** Error code 1
> 
> Stop.
> make[1]: stopped in /usr/ports/lang/perl5.24
> *** Error code 1
> 
> Stop.
> make: stopped in /usr/ports/lang/perl5.24

**Comment by raphidae** [comment]
Just hit the same problem on df7e42455b9(hardened/11-stable/master-libressl) for 5.26

mpdtrace/opmini.o: In function `Perl_op_clear':
opmini.c:(.text+0xb9a): undefined reference to `__safestack_unsafe_stack_ptr'
opmini.c:(.text+0xe7f): undefined reference to `__safestack_unsafe_stack_ptr'
mpdtrace/opmini.o: In function `Perl_custom_op_get_field':
opmini.c:(.text+0x1839): undefined reference to `__safestack_unsafe_stack_ptr'
opmini.c:(.text+0x1ad8): undefined reference to `__safestack_unsafe_stack_ptr'
mpdtrace/opmini.o: In function `S_gen_constant_list':
opmini.c:(.text+0x337a): undefined reference to `__safestack_unsafe_stack_ptr'
mpdtrace/opmini.o:opmini.c:(.text+0x3565): more undefined references to `__safestack_unsafe_stack_ptr' follow
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** [lib/buildcustomize.pl] Error code 1

make[2]: stopped in /usr/ports/lang/perl5.26/work/perl-5.26.1
1 error
