### ISSUE TITLE
Cannot build shells/bash with STATIC set.

### ISSUE THREAD

**Issue by chrcoluk** [HardenedBSD/hardenedbsd-ports#6]
I have tried with and without the hardening flags.

The attached log output is with no make.conf to rule that out as the culprit.

It seems to be a linker error related to libc during the make install part of the process, portmaster ends up also thinking its successful which is why I didnt initially notice this problem.

Flags activated in config dialog box are.
COLONBREAKSWORDS
HELP
NLS
STATIC

FreeBSD shiva.chrysalisnet.org 11.0-STABLE-HBSD FreeBSD 11.0-STABLE-HBSD #0 646da84b22f(hardened/11-stable/master)-dirty: Tue Jan 31 15:43:29 GMT 2017

[bashfail.txt](https://github.com/HardenedBSD/hardenedbsd-ports/files/742470/bashfail.txt)

**Comment by lattera** [comment]
Purely by coincidence, I've already started investigating this issue.

**Comment by lattera** [comment]
This should now be fixed. Please re-open this issue if you have further problems.
