### ISSUE TITLE
Unable to build openjdk[678] on v46.18 using poudriere

### ISSUE THREAD

**Issue by utrenkner** [HardenedBSD/hardenedbsd-ports#60]
Hi, I set up poudriere on v46.18 and compiled a number of ports. But I am unable to get any of the openjdk-versions built. v8 depends on v7 and this one as well as v6 complain about a wrong (or missing?) version of ant. As java/bootstrap-openjdk builds fine, I think it might be that openjdk is just not able to read the version string - here is the error message from the build process for openjdk7 (looks very similar of openjdk6).
```
ERROR: The version of ant being used is older than \n       the required version of '1.7.1'. \n       The version of ant found was '# # A fatal error has been detected by the Java Runtime Environment: # #  SIGSEGV (0xb) at pc=0x000002b4e4b12060, pid=1863, tid=1015266.0'. \n 
ERROR: Your BOOTDIR environment variable does not point \n       to a valid JDK for bootstrapping this build. \n       A JDK 7  build must be bootstrapped using  \n       JDK 1.6. fcs (or later). \n       Apparently, your bootstrap JDK is version # \n       Please update your ALT_BOOTDIR setting and start your build again. \n 
Exiting because of the above error(s). \n
```
As I see that you offer openjdk6 packages, I was wondering, how you overcame this issue?

**Comment by lattera** [comment]
When building packages, it's best to disable PaX NOEXEC:

```
# sysctl hardening.pax.pageexec.status=1
# sysctl hardening.pax.mprotect.status=1
```

When I get back to my laptop, I can send you the sysctl.conf I use on our official package building server.

**Comment by Beeblebrox-BSD** [comment]
I had asked about settings needed for poudriere builds on the users mail list some time ago, but no one answered. If it's not a big secret, the settings should be on a wiki page or Handbook.

I know it's not possible to set separate sysctls on a per-jail basis, I wonder if it would be possible to do so if poudriere is placed in a virtual env like bhyve/xen so as not to tamper with host-level sysctls (probably not).

**Comment by lattera** [comment]
Sorry for the delay. Work got really busy. Here's the sysctl.conf I use on our package building box:

```
hardening.pax.aslr.status=1
hardening.pax.aslr.compat.status=1
hardening.pax.segvguard.status=1
hardening.pax.pageexec.status=1
hardening.pax.mprotect.status=1
hardening.procfs_harden=0
hardening.pax.disallow_map32bit.status=1
security.bsd.hardlink_check_gid=0
security.bsd.hardlink_check_uid=0
debug.debugger_on_panic=0
```

**Comment by utrenkner** [comment]
Sorry, I forgot to let you know that with the [two sysctls](https://github.com/HardenedBSD/hardenedbsd-ports/issues/60#issuecomment-312883388) mentioned by @lattera, I was able to build both, openjdk7 and 8 without any further problems. Therefore I close this issue, now.

But, I second @Beeblebrox-BSD 's suggestion to put this info somewhere in the Handbook or wiki. Maybe even in a sort of how-to for using poudriere on HardenedBSD.
