### ISSUE TITLE
www/h2o builds and runs perfectly with PIE and SAFESTACK configured

### ISSUE THREAD

**Issue by utrenkner** [HardenedBSD/hardenedbsd-ports#61]
Today, I built [www/h2o](https://github.com/HardenedBSD/hardenedbsd-ports/tree/master/www/h2o) and can confirm that it runs fine with PIE and SAFESTACK. I think you can safely set these as defaults for this port.

I include FreeBSD's ports maintainer @dhc for info.

**Comment by lattera** [comment]
Thanks for the info! No need to involve FreeBSD since these options are only available for HardenedBSD. Options like PIE and SafeStack only make sense for operating systems that have ASLR.

**Comment by utrenkner** [comment]
Yes, I am aware that it does not have any relevance for FreeBSD itself - but I think it makes sense to let the maintainer know, nevertheless. It is an interesting info that "his" port runs also in a safer mode on HardenedBSD.

**Comment by lattera** [comment]
Yup. I'll take a look at this later today.

**Comment by lattera** [comment]
I've now merged in the fix for this. Thanks!
