### ISSUE TITLE
mozilla ports fail to build

### ISSUE THREAD

**Issue by Beeblebrox-BSD** [HardenedBSD/hardenedbsd-ports#64]
All mozilla based ports (www/libxul, www/firefox, www/seamonkey) break with:
"/usr/bin/ld: error: unknown argument: --warn-unresolved-symbols"

All hardening sysctls disabled and secadm flushed via script. java & math/R related ports were able to build.

I find my situation pretty humorous, as I'm using a hardened OS but a browser (qupzilla) that does not have javascript blocking :P

**Comment by lattera** [comment]
This is due to ld.lld and is a known problem. Upstream FreeBSD is working with the llvm folks to provide a solution. For now, rebuild world with WITHOUT_LLD_IS_LD set in src.conf. Or remove the /usr/bin/ld symlink and relink it to /usr/bin/ld.bfd.

**Comment by Beeblebrox-BSD** [comment]
Thanks I saw the PR on Bugzilla after your post. Works now.
