### ISSUE TITLE
Trying to make sense of ports that require lib32

### ISSUE THREAD

**Issue by Beeblebrox-BSD** [HardenedBSD/hardenedbsd-ports#65]
Several important ports fail to build due to missing x86 compat.
For example:

* emulators/virtualbox: Missing /usr/lib32

* emulators/qemu-devel (vanilla config settings):
Building optionrom/multiboot.img
ld: error: do not know how to handle relocation 'R_X86_64_16' (12)

* math/fityk: can't handle relocation R_X86_64_PC32

I assume HBSD poudriere build env have /usr/lib32 and COMPAT 32 to build these ports, but I imagine  the binaries would not run on HBSD host even if built in a lib32 enabled environment since HBSD default (as previously discussed) is to omit 32-bit.

So why does HBSD have packages for these in its repo? Should users who wish to use these ports build world/kernel with COMPAT 32 included?

**Comment by lattera** [comment]
Some packages only need 32-bit compat for the build process, like emulators/virtualbox-ose. Here's the src.conf from the pkg building server:

```
WITH_LIB32=yes
MALLOC_PRODUCTION=yes
#WITH_LIBRESSL=yes
WITHOUT_RELRO=yes
WITHOUT_BIND_NOW=yes
WITHOUT_LLD_IS_LD=yes
WITHOUT_LLD_BOOTSTRAP=yes
WITHOUT_TESTS=yes
#WITH_SYSTEM_COMPILER=yes
```

**Comment by Beeblebrox-BSD** [comment]
Thanks for this. Does HBSD require unset of
MALLOC_PRODUCTION=yes
for normal operation? I've had this setting before switching to HBSD, and I wonder if HBSD uses and needs the MALLOC framework to enforce Hardening?

**Comment by lattera** [comment]
Setting MALLOC_PRODUCTION is only needed for -CURRENT, since FreeBSD -CURRENT sets jemalloc debug mode by default. jemalloc is in production mode for all -STABLE and -RELEASE branches.

I only set it on the package building box so I get better performance. Package builds take around 42 hours right now. And we maintain four package repos, all built by the same server. So performance is critical on that machine.

**Comment by lattera** [comment]
I'm wondering if this issue simply comes down to documentation. I'm working (slowly) on the HardenedBSD Handbook. I think that HardenedBSD having 32-bit compatibility disabled by default should be documented there.

Would it be more appropriate to close this ticket and open a new one in HardenedBSD/hardenedbsd-doc to track documenting this?

**Comment by Beeblebrox-BSD** [comment]
Hi.

> Would it be more appropriate to close this ticket and open a new one
My last comment was asking whether jemalloc is an integral infrastructure part of any HBSD feature - as an absurd example, "pax.pageexec uses existing jemalloc calls, thus kernels must be built with jemalloc". Your answer clarifies that, and no it!s not required. The MALLOC Q did not seem logically consistent to me either, but I had a nagging doubt. Otherwise, I've been setting MALLOC off since 10-Current.

> I'm wondering if this issue simply comes down to documentation.
My suggestion: Currently the HBSD docs is integrated with the full FreeBSD Handbook. HBSD should have its own full Handbook, but you might consider a separate abridged HBSD document for those who are already familiar with FreeBSD - short & sweet:
sysctls, src.conf/kern.conf, secadm, poudriere settings (we have to build two worlds & modify sysctls prior to build start), then whatever else I've overlooked here.

Not everyone has a server room; some, like me, might be doing everything on a desktop machine.

Regards
