### ISSUE TITLE
Problem with safestack and www/h2o

### ISSUE THREAD

**Issue by utrenkner** [HardenedBSD/hardenedbsd-ports#67]
Earlier, I reported success in using [www/h2o with the safestack option](https://github.com/HardenedBSD/hardenedbsd-ports/issues/61). Unfortunately, I noticed cases in which this option breaks h2o, consistently. Therefore, please turn it off, again.

**Comment by lattera** [comment]
Sounds good. I'll revert the commit enabling SafeStack for www/h2o. Can you document here what you noticed?

**Comment by utrenkner** [comment]
Generally, the h2o webserver seems to work as normal. But on some requests it throws an Internal Server Error (503). This happens on certain requests to the php-fpm server. The /var/log/h2o/h2o-error.log then says this:
```
[lib/handler/fastcgi.c] in request:/www/delivery/ck.php?oaparams...:received broken response
```
The PHP app running on that server (and to which ck.php belongs) is the [Revive adserver](https://www.revive-adserver.com/). 

Without SafeStack, this error and the subsequent 503 HTTP status do not appear. I have looked at the fastcgi traffic but could not easily spot the trigger for this behaviour. Thus, I do not know, whether h2o passes wrong data to php-fpm or whether it cannot handle the otherwise correct answer from php-fpm. I suspect the latter.

Compiling h2o as PIE seems to have no influence on this error. So PIE can be left turned on.
