### ISSUE TITLE
[www/nginx-full] LibreSSL build error

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedbsd-ports#8]
Log attached.

[nginx-full-1.10.3,2.log.txt](https://github.com/HardenedBSD/hardenedbsd-ports/files/768423/nginx-full-1.10.3.2.log.txt)

**Comment by Sp1l** [comment]
Fixed by 9b7ec1cd853bdab3da253c529fc125cf8773e197
See also: https://github.com/grahamedgecombe/nginx-ct/pull/17
